/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

public class App {
    public static void main(String[] args) {
        Pizzeria p = new Pizzeria();
        p.solve();
        p.createFile();
    }
}
